### ISSUE TITLE
Class 'CMSPACA\RtSimpleosm\Hooks\PageLayoutViewDrawItemHook' not found

### ISSUE THREAD

**Issue by SirCotare** [Treedent/rt_simpleosm#1]
I'm using composer mode.

Error is:
`Class 'CMSPACA\RtSimpleosm\Hooks\PageLayoutViewDrawItemHook' not found`

Class name is not matching file name in:
`Classes/Hooks/PageLayoutView.php`

Renaming the file to "PageLayoutViewDrawItemHook.php" will solve the issue. Thanks.

**Comment by Treedent** [comment]
Thank you for the tip.

It will be included in the next release.
