### ISSUE TITLE
some markers are not displayed

### ISSUE THREAD

**Issue by jwbdv** [Treedent/rt_simpleosm#8]
hi :-)

i added a lot of marker to one map.
If got 2 which are allready the same, but one is not displayed in the map.
I can find the json entry in the markup, but it is not displayed.

**Comment by Treedent** [comment]
Hi,
what do you mean by already the same ?

**Comment by jwbdv** [comment]
sry
"almost"

is there a limit of entries?

**Comment by jwbdv** [comment]
ok, got it

it wasn´t displayed because it was to close together
